introducing Error

diff --git a/.github/workflows/action-terraform-verify.yml b/.github/workflows/action-terraform-verify.yml
--- a/.github/workflows/action-terraform-verify.yml
+++ b/.github/workflows/action-terraform-verify.yml
@@ -45,6 +45,7 @@ jobs:
               if [[ $FMT_STATUS -ne 0 ]]; then
                 echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
                 echo "CHECK_STATUS=1" >> $GITHUB_ENV
+                exit 1  # 🚨 Stops workflow on failure
               fi
             fi
           done
